### ISSUE TITLE
Submodule distribution to standalone tool

### ISSUE THREAD

**Issue by pieterhijma** [movedo/MoVeDo#10]
As of now, MoVeDo is quite invasive into a project since MoVeDo is essentially distributed by means of a submodule into a project. For my projects, I would prefer MoVeDo to be a standalone tool. I could see two different solutions where one is more different from the current setup than the other: 

- clone MoVeDo in a directory outside the project and refer to it with an environment variable such as MOVEDO_DIR,
- create full blown releases of the tool.

The two options don't exclude each other by the way, where the former is for development purposes and the latter for more stable solutions.

**Comment by hoijui** [comment]
Makes sense!
But how exactly to do it... not sure I am.
There is already a MoVeDo docker image, which is used when building a projects documents in CI.
To use that on a local machine, would be quite heavy and clunky though, for my taste.
The problem is, that MoVeDo is quite leight-weight, but uses a lot of other tools (pandoc, panflute, BASH/UNIX tools, ...), which themselves have their particularities, and separate package managers to install them, and what not.
... Then again.. this is already the case now, and we can just leave it as is.

Yeah.. to combine your two approaches would make sense to me. have it in a separate dir, but as a git repo, and use git for updating. One potential issue, is if there would be backwards incompatibilities (which the current approach handles well), but that should not happen too much in practice, or say, we could consider it a bug to be fixed. at least so it was until now.

The docker image approach already uses the `MOVEDO_DIR` env way of doing things.

**Comment by hoijui** [comment]
d87736dcba12eea42d60b6b0d318c16f560207b4 adds the bash script `bin/mvd`,
which simply redirects to all the commands under `scripts/`.
I tried it locally, and it seems to work.
Meaning.. this should already... mostly... be it,
aside form changing the documentation and CI scripts and so on, to reflect this change.

**Comment by pieterhijma** [comment]
Thanks, great work!

**Comment by hoijui** [comment]
Note to self:
Only documenting this (in the README) is missing.

**Comment by hoijui** [comment]
done!
(see README)
